### ISSUE TITLE
Poder descargar librería desde gestor de dependencias 

### ISSUE THREAD

**Issue by sherzo** [ApamateSoft/Validator#2]
Sería muy útil poder descargar esta librería desde alguna gestor de dependencias como por ejemplo `maven`

**Comment by ApamateSoft** [comment]
Saludos.
Se acaba de publicar la versión 1.2.0 de Validator. ya es posible descargar esta librería como dependencia, puedes revisar la documentación, allí se indica como implementar Validator tanto en Gradle como en Maven.
